# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  onlineexamuserserviceapi:
    image: onlineexamuserserviceapi
    build:
      context: .
      dockerfile: OnlineExam.UserService.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7083:7083
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
